name: Install and test MagicaPanel
on:
  push:
    branches:
      - master
    pull_request:
      paths-ignore:
        - "*.md"
        - "attachment/**"
        - "LICENCE"
jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ^18
          cache: npm
      - name: Upgrade npm
        run: npm install --global npm@^8.18
      - run: npm install --no-audit
      - run: npm run test:ci

  xo:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ^18
          cache: npm
      - name: Upgrade npm
        run: npm install --global npm@^8.18
      - run: npm install --no-audit
      - run: npm run lint
